#ifndef __DEFAULT_DEFS_H_
#define __DEFAULT_DEFS_H_

#define DEFAULT_SYSTEMTICK 		1
#define DEFAULT_HEARTBEATTICK		2
#define DEFAULT_UPLOADMONIDATATICK 	3
#define DEFAULT_DBPATH 			"tcp://127.0.0.1:3306"
#define DEFAULT_DBUSER			"root"
#define DEFAULT_DBPASSWD 		"kevinLike$"
#define DEFAULT_DBNAME 			"omsdb"
#define DEFAULT_CMAID 			"22M00000022376016"
#define DEFAULT_LOCALIP 		"127.0.0.1"
#define DEFAULT_PROXYIP 		"127.0.0.1"
#define DEFAULT_PORT 			6000

#define DEFAULT_UPDATE_INTERVAL_COUNTER 5
#endif
